<?xml version="1.0"?>
<package format="3">
  <name>simple_mover</name>
  <version>0.0.0</version>
  <description>ROS 2 inverse kinematics and XY position tracking.</description>
  <maintainer email="farid@example.com">Farid Surya Wardana</maintainer>
  <license>Apache-2.0</license>
  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
